// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart"
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import "firebase_options.dart";
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for windows - "
              "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for linux - "
              "you can reconfigure this by running the FlutterFire CLI again.",
        );
      default:
        throw UnsupportedError(
          "DefaultFirebaseOptions are not supported for this platform.",
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment("API_KEY_WEB"),
    appId: String.fromEnvironment("APP_ID_WEB"),
    messagingSenderId: String.fromEnvironment("MESSAGING_SENDER_ID"),
    projectId: "shokuhi-beda8",
    authDomain: "shokuhi-beda8.firebaseapp.com",
    storageBucket: "shokuhi-beda8.appspot.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment("API_KEY_ANDROID"),
    appId: String.fromEnvironment("APP_ID_ANDROID"),
    messagingSenderId: String.fromEnvironment("MESSAGING_SENDER_ID"),
    projectId: "shokuhi-beda8",
    storageBucket: "shokuhi-beda8.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment("API_KEY_IOS"),
    appId: String.fromEnvironment("APP_ID_IOS"),
    messagingSenderId: String.fromEnvironment("MESSAGING_SENDER_ID"),
    projectId: "shokuhi-beda8",
    storageBucket: "shokuhi-beda8.appspot.com",
    iosClientId: String.fromEnvironment("IOS_CLIENT_ID"),
    iosBundleId: "com.example.shokuhi",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment("API_KEY_MACOS"),
    appId: String.fromEnvironment("APP_ID_MACOS"),
    messagingSenderId: String.fromEnvironment("MESSAGE_SENDER_ID"),
    projectId: "shokuhi-beda8",
    storageBucket: "shokuhi-beda8.appspot.com",
    iosClientId: String.fromEnvironment("IOS_CLIENT_ID"),
    iosBundleId: "com.example.shokuhi",
  );
}